### ISSUE TITLE
GitHub Action unable to compute my documentation diff

### ISSUE THREAD

**Issue by sandcht** [bump-sh/github-action#246]
i used this GitHub Action  as expected but I'm now facing this error 

![Capture d’écran 2022-05-11 à 08 55 23](https://user-images.githubusercontent.com/99471869/167790034-51ce8561-41c5-4234-8b8d-7af84090b68f.png)
<img width="580" alt="Capture d’écran 2022-05-11 à 08 55 46" src="https://user-images.githubusercontent.com/99471869/167790050-e0748e14-af9a-46bd-893a-29bd118c404e.png">

**Comment by paulRbr** [comment]
Hello @sandcht, thanks for reporting the issue.

It seems our servers had some small difficulties this morning to compute your diff and due to some overloaded queue we didn't process your diff in time (within 30 seconds of the waiting time of the Github-Action). But it should be fine if your retry anytime now.

Please let us know if you still have any issue. Thanks!
